### ISSUE TITLE
Current Time

### ISSUE THREAD

**Issue by dc0d** [rs/xid#12]
Using `time.Now()` for getting current time is problematic, when we are using this package, running on different servers with different timezones. Seems logical to use `time.Now().UTC()` as default - a sane default. Or add some package (or type level) default function for getting current time, that one could change if needed:

```go
var (
	TimeFunc = func() time.Time {
		return time.Now().UTC()
	}
)
```

**Comment by rs** [comment]
Thx for the heads-up. That was indeed a mistake not to use UTC time.

**Comment by rs** [comment]
That being said, `Unix` does always return an UTC time.

**Comment by rs** [comment]
I reverted the change. Please provide more context if you think I'm missing something.

**Comment by dc0d** [comment]
You are right. The documentation for `Unix()` was not clear to me. My apologies; and Thanks!
