### ISSUE TITLE
Add a id pool layer

### ISSUE THREAD

**Issue by bestplay** [rs/xid#13]
```
userid_pool := xid.NewPool()
orderid_pool := xid.NewPool()

userid := userid_pool.New()
orderid := userid_pool.New()
```

Keep idCounter in different pool 

Ids in the same pool are unique.

But in different pools, ids do not need to be unique.

**Comment by rs** [comment]
What is the use-case? I'm not sure to understand.

**Comment by bestplay** [comment]
I want to use xid to generate user id and order id.

If id counter is global, the counter will consumes quick.

So maybe i need seperate counter in different pools..

**Comment by rs** [comment]
You can generate 2^24 ids per second per server before exhausting the counter. Even if you are running Facebook, it would be more than enough :)

**Comment by bestplay** [comment]
ok, my bad,

haha
