### ISSUE TITLE
Usage in docker

### ISSUE THREAD

**Issue by vincentserpoul** [rs/xid#17]
I'm always running my golang executables within containers in docker.
The PID is then always 1, which then defeats the purpose of having this field.

Would there be any possible replacement?

The least would be to specify this caveat in the README I think.

**Comment by rs** [comment]
What about hashing the content of `/cpu/1/cpuset` if the PID is 1 and the file exists?

**Comment by rs** [comment]
Please check b25bb5a and tell me if it would fix your issue.

**Comment by vincentserpoul** [comment]
Quick response!
Yes, it does work perfectly.
I ran benchmarks within docker, the performance doesn't seem affected as well.
