### ISSUE TITLE
Out of Sequence ID

### ISSUE THREAD

**Issue by dc0d** [rs/xid#26]
An out of sequence phenomena can be seen by running this code (or there is a mistake in my approach). This code simply compare two ids, generated consecutively:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/rs/xid"
)

func main() {
	var (
		p, n []byte
	)

	var cnt int64
	for p, n = nil, []byte("0"); bytes.Compare(p, n) < 0; p, n = n, next() {
		cnt++
	}

	idp := conv(p)
	idn := conv(n)
	fmt.Printf("%v %s %s\n", cnt, idp.String(), idn.String())
}

func next() []byte {
	id := xid.New()
	return id[:]
}

func conv(b []byte) xid.ID {
	var id xid.ID
	copy(id[:], b)
	return id
}
```

Sample outputs:

```
6135364 bah53vtgl2r1p4vvvvvg bah53vtgl2r1p4o00000
2586623 bah540dgl2r1q1fvvvvg bah540dgl2r1q1800000
3508359 bah55elgl2r1sdfvvvvg bah55elgl2r1sd800000
```

**Comment by rs** [comment]
You are overflowing the counter. The counter is on 3 bytes and is init with a random number. With this technique, you can even generate twice the same id if your machine is able to generate more than 1<<24 ids per second.
