### ISSUE TITLE
Bug: hostid_windows.go: "Undefined: windows"

### ISSUE THREAD

**Issue by cdepauw** [rs/xid#32]
In hostid_windows.go you forgot importing the "windows" reference :)

**Comment by ntulsy** [comment]
I believe I ran into the issue with latest version: 

vendor\github.com\rs\xid\hostid_windows.go:10:39: readPlatformMachineID redeclared in this block
        previous declaration at vendor\github.com\rs\xid\hostid_fallback.go:7:39
vendor\github.com\rs\xid\hostid_windows.go:12:8: undefined: windows
vendor\github.com\rs\xid\hostid_windows.go:13:9: undefined: windows
vendor\github.com\rs\xid\hostid_windows.go:17:8: undefined: windows
vendor\github.com\rs\xid\hostid_windows.go:25:8: undefined: windows
vendor\github.com\rs\xid\hostid_windows.go:30:12: undefined: windows

**Comment by rs** [comment]
Oops sorry about that.
