### ISSUE TITLE
Question around readMachineID

### ISSUE THREAD

**Issue by sata** [rs/xid#81]
Thank you for your work! I've been using it as an inspiration for ID generation for a particular project. 

I'm most likely wrong here, but I'm curious to verify my understanding. Feel free to ignore the question, and just close the ticket! 

I cannot see how [readMachineID](https://github.com/rs/xid/blob/master/id.go#L113) is stable. 

```go
func readMachineID() []byte {
	id := make([]byte, 3)
	hid, err := readPlatformMachineID()
	if err != nil || len(hid) == 0 {
		hid, err = os.Hostname()
	}
	if err == nil && len(hid) != 0 {
		hw := md5.New()
		hw.Write([]byte(hid))
		copy(id, hw.Sum(nil))
	} else {
		// Fallback to rand number if machine id can't be gathered
		if _, randErr := rand.Reader.Read(id); randErr != nil {
			panic(fmt.Errorf("xid: cannot get hostname nor generate a random number: %v; %v", err, randErr))
		}
	}
	return id
}
```

Assuming a Linux platform, `readPlatformMachineID` would return according to the `man machine-id`:

> The machine ID is a single newline-terminated, hexadecimal, 32-character, lowercase ID

If we successfully read it, and the length is correct, we then md5 hash it, and copy only the 3 first bytes out of 16 bytes.

Wouldn't this be prone to collisions as we are only using the 3 first bytes of the md5 hash?

I wrote a tiny test, following the same approach but randomly generating the string to be feed into the hash
```go
package unique

import (
	"crypto/md5"
	"math/rand"
	"testing"
)

const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func randStr(r *rand.Rand) string {
	b := make([]byte, 32)
	for i := range b {
		b[i] = chars[r.Intn(len(chars))]
	}
	return string(b)
}

func genID(hid string) []byte {
	id := make([]byte, 3)
	hw := md5.New()
	hw.Write([]byte(hid))
	copy(id, hw.Sum(nil))
	return id
}

func TestUnique(t *testing.T) {
	r := rand.New(rand.NewSource(999))

	rounds := 100000

	mStr := map[string]interface{}{}
	mID := map[string]string{}

	for i := 0; i < rounds; i++ {
		src := randStr(r)
		_, ok := mStr[src]
		if ok { // skip when we've already randomly generated the same string as source
			continue
		}
		mStr[src] = struct{}{}

		genID := string(genID(src))
		storedSrc, ok := mID[genID]
		if ok {
			t.Fatalf("collision? round: %d, storedSrc: '%s', src: '%s', id: '%v'",
				i, storedSrc, src, genID)
		}
		mID[genID] = src
	}
}

func TestCollision(t *testing.T) {
	src1 := "pplbyfSYmSkuUQbjJvcOWsUuSwoPYOTk"
	src2 := "LRnRfzVvPAWbEhDNOegktwBvpaCnutyH"
	require.NotEqual(t, genID(src1), genID(src2))
}
```

```output
➜  unique go test -v ./...
=== RUN   TestUnique
    unique_test.go:48: collision? round: 12209, storedSrc: 'pplbyfSYmSkuUQbjJvcOWsUuSwoPYOTk', src: 'LRnRfzVvPAWbEhDNOegktwBvpaCnutyH', id: '�(m'
--- FAIL: TestUnique (0.01s)
=== RUN   TestCollision
    unique_test.go:58: 
        	Error Trace:	unique_test.go:58
        	Error:      	Should not be: []byte{0xa3, 0x28, 0x6d}
        	Test:       	TestCollision
--- FAIL: TestCollision (0.00s)
FAIL
FAIL	github.com/sata/unique	0.013s
FAIL

```

My take of it is, after 12209 attempts, we ended up with two identical machine IDs while their sources are different.

Is the xid ID considered to be stable since we take epoch time + machine identifier + local process id + start counter at a random value? i.e the likelihood of there being a collision of xid IDs is so low due to the other factors?

**Comment by rs** [comment]
It's basically a 24bit ID for the machin, which is indeed not collision free. Yes it is combinaison of all the factors which are making it globally unique without coordination.

**Comment by huoding** [comment]
Since all factors(time, machine_id, process_id, counter) can be same, how can we making xid globally unique

**Comment by rs** [comment]
On the same machine with same pid, you are in the same process and thus the counter is atomically incremented and as a consequence will not generate twice the same ID.

**Comment by huoding** [comment]
I mean two different machines might produce the same machine id (because only 3 bytes)
Once the other factors are the same, how can we making xid globally unique

**Comment by sata** [comment]
Apologies for not getting back to this thread. I had to do quite a bit of reading to understand the probabilities. Maths isn't my strong suit. 

Assuming a context of running a Go program as part of a container, wouldn't the local process ID be 1 as well?

That would leave us with  random counter value and the machine id, since epoch time would most likely be the same across all machines (assuming time is perfectly calibrated of course, which it isn't).
 
> I mean two different machines might have the same machine id (because only 3 bytes) Once the other factors are the same, how can we making xid globally unique

To answer this, one has to think about the _probabilities_ of the machine ID being the same.

Given [Probability of a shared birthday (collision)](https://en.m.wikipedia.org/wiki/Birthday_problem#Probability_of_a_shared_birthday_(collision))

One can play around in R to understand the probabilities a bit better

```R
> p <- function(n,d) 1 - exp(-n*(n-1)/(2*d))
> p(n=2, d=16777216)
[1] 5.960464e-08
> p(n=10, d=16777216)
[1] 2.682205e-06
> p(n=20, d=16777216)
[1] 1.132482e-05
> p(n=50, d=16777216)
[1] 7.301302e-05
> p(n=100, d=16777216)
[1] 0.0002949995
> p(n=250, d=16777216)
[1] 0.001853475
> p(n=500, d=16777216)
[1] 0.007408103
> 
```  

`n` is the number of machines, `d` is the maximum value you can represent with 3 bytes. 

The probability here is only for the machine id on it's own. If we were to consider the fact that IDs also start at a random value, the probability of collisions is of course even less. I didn't attempt to calculate that aspect due to lack of time, I wish I had taken statistics at university! 
 
For 500 machines, the probability is quite high that there will be a collision on just the machine ID.  But for even 20 or 50 machines, not so much.
