### ISSUE TITLE
What is "K-ordered" and "sortable"?

### ISSUE THREAD

**Issue by natenho** [rs/xid#86]
Hi! Could you please explain what exactly is `K-ordered` and `sortable`? I'm not sure if I got the meaning of these aspects compared to other approaches.

Does that mean by any chance that the xid generated at two distinct moments e.g. start of today will necessarily be sorted before any xid generated afterwards (behaving like a timestamp)?

Thank you! :)

**Comment by rs** [comment]
Correct.
