### ISSUE TITLE
Command-line tool

### ISSUE THREAD

**Issue by sergeevabc** [rs/xid#92]
Dear @rs,
I'm not sure how to appreciate the beauty of your solution without being able to run it on Windows as a binary that produces the result. E.g. check [ULID](https://github.com/oklog/ulid/) and [CUID](https://github.com/xaevik/cuidgen)v2

```console
$ ulid.exe
01GPR0A4J919E253QDAGVR8MK7

$ cuidgen.exe
gib227a07c6a1njttd9jn982
```

**Comment by rs** [comment]
This is a library. You can import it and build a cli in a few lines of code.
